name: Streamer Alerts Poller

on:
  schedule:
    # Šis automātiski iedarbinās botu ik pēc 10 minūtēm
    - cron: '*/10 * * * *'
  workflow_dispatch: # Saglabā pogu manuālai palaišanai

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy commands
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: npm run deploy

      - name: Run Alert Check
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CRON_MODE: "true" 
        run: npm start
